import type { GlobalThemeOverrides } from 'naive-ui'

export const themeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#4F6BED',
    primaryColorHover: '#6A82F0',
    primaryColorPressed: '#3F58D1',
    primaryColorSuppl: '#4F6BED',
    successColor: '#059669',
    warningColor: '#EA580C',
    errorColor: '#E11D48',
    infoColor: '#0284C7',
    bodyColor: '#F4F6FA',
    cardColor: '#FFFFFF',
    modalColor: '#FFFFFF',
    popoverColor: '#FFFFFF',
    inputColor: '#FFFFFF',
    tableColor: '#FFFFFF',
    tableHeaderColor: '#F1F4F9',
    borderColor: 'rgba(15,23,42,0.10)',
    dividerColor: 'rgba(15,23,42,0.08)',
    textColorBase: '#0F172A',
    textColor1: '#0F172A',
    textColor2: '#1E293B',
    textColor3: '#475569',
    placeholderColor: '#94A3B8',
    borderRadius: '8px',
    borderRadiusSmall: '6px',
    fontFamily: 'Inter, "PingFang SC", "Noto Sans SC", system-ui, sans-serif',
    fontFamilyMono: '"JetBrains Mono", "SF Mono", Menlo, monospace',
    fontSize: '14px',
    fontSizeSmall: '13px',
    fontSizeMedium: '14px',
    fontSizeLarge: '15px',
  },
  Button: { borderRadiusMedium: '8px', fontWeight: '500' },
  Card: { borderRadius: '12px', color: '#FFFFFF' },
  Input: { color: '#FFFFFF', colorFocus: '#FFFFFF', border: '1px solid rgba(15,23,42,0.12)' },
  DataTable: { thColor: '#F1F4F9', tdColor: '#FFFFFF', borderColor: 'rgba(15,23,42,0.08)' },
  Tag: { borderRadius: '999px' },
  Tabs: { tabTextColorLine: '#475569', tabTextColorActiveLine: '#0F172A', barColor: '#4F6BED' },
}
